Addition of guide to how to download dependencies
nexmo-community/dial-a-carol pull request #1
Opened 2020-10-01 07:37 UTC by Kerveyfelix

To make this Repository more user friendly, I have added resources for installing dependencies.
I have made the following changes in the README.md file:
1) Added the link to download the Python 3.x version for Python's site.
2)  Add the commands to add Requests and Flask package in Python.

2020-10-01 09:04 UTC, martyndavies requested changes
Thanks for your contribution. You have spelling mistakes on the word 'install' in the added text, please can you fix that and recommit the changes.

2020-10-01 09:37 UTC, Kerveyfelix commented
I have rectified the spelling mistakes. Kindly review @martyndavies

2020-10-01 09:52 UTC, martyndavies requested changes

2020-10-01 09:52 UTC, martyndavies commented on README.md
> +-Use the following command in your terminal to install Request: pip install requests
We use backticks to highlight commands that people should execute, for example `pip install requests`, please can you update to include these?

2020-10-13 10:32 UTC, martyndavies commented
@Kerveyfelix Are you going to be able to make these changes?

2020-10-14 08:40 UTC, Kerveyfelix commented
@martyndavies I am making the changes now.

2020-10-14 08:51 UTC, Kerveyfelix commented
@martyndavies  Can you review my PR? I have added backticks.

2020-10-14 09:41 UTC, martyndavies approved these changes

2020-10-14 09:43 UTC, merged